Repository pagopa/pagopa-afm-calculator, pull requests merged in 2022-11, with the labels that each got.

#34 feat: [PGEC-86] Added info to bundle
  src/main/java/it/gov/pagopa/afm/calculator/entity/Bundle.java
  src/main/java/it/gov/pagopa/afm/calculator/model/bundle/BundleInfo.java
Labels: enhancement

#36 Github Action - Auto update Openapi
  .github/workflows/update_openapi.yml
  docker/run_docker.sh
  openapi/generate_openapi.sh
  openapi/openapi-node.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/afm/calculator/model/BundleType.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentMethod.java
  src/main/java/it/gov/pagopa/afm/calculator/model/Touchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/model/TransferCategoryRelation.java
Labels: ignore-for-release

#37 [PGEC-32] BDD Test Marketplace
  integration-test/src/config/.env.local
  integration-test/src/config/data.json
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/yarn.lock
  src/main/java/it/gov/pagopa/afm/calculator/model/bundle/BundleInfo.java
  src/main/java/it/gov/pagopa/afm/calculator/model/bundle/CiBundleAttribute.java
  src/main/java/it/gov/pagopa/afm/calculator/model/configuration/CiBundle.java
  src/main/java/it/gov/pagopa/afm/calculator/model/configuration/Configuration.java
  src/main/resources/application-local.properties
Labels: enhancement

#35 [PGEC-84] Touchpoints refactoring
  .github/workflows/update_openapi.yml
  src/main/java/it/gov/pagopa/afm/calculator/entity/Bundle.java
  src/main/java/it/gov/pagopa/afm/calculator/entity/Touchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOptionByPsp.java
  src/main/java/it/gov/pagopa/afm/calculator/model/Touchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/model/calculator/Transfer.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/test/java/it/gov/pagopa/afm/calculator/TestUtil.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/requests/setConfiguration.json
  src/test/resources/responses/getFees.json
  src/test/resources/responses/getFees2.json
  src/test/resources/responses/getFees_noInTransfer.json
Labels: enhancement

#45 [PGEC-87] Digital Stamp
  src/main/java/it/gov/pagopa/afm/calculator/model/BundleType.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentMethod.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
  src/main/java/it/gov/pagopa/afm/calculator/model/Touchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/model/TransferCategoryRelation.java
  src/main/java/it/gov/pagopa/afm/calculator/model/TransferListItem.java
  src/main/java/it/gov/pagopa/afm/calculator/model/calculator/Transfer.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/test/java/it/gov/pagopa/afm/calculator/TestUtil.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/requests/getFees_digitalStamp.json
  src/test/resources/requests/getFees_digitalStamp2.json
  src/test/resources/responses/getFees.json
  src/test/resources/responses/getFees2.json
  src/test/resources/responses/getFees_noInTransfer.json
Labels: enhancement

#46 [PGEC-101] calculator fix integration test
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .devops/template/maven-github-release.yaml
  .github/workflows/update_openapi.yml
  docker/CosmosDB.Dockerfile
  docker/run_docker.sh
  integration-test/src/config/data.json
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/yarn.lock
  openapi/openapi-node.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/afm/calculator/controller/ConfigurationController.java
  src/main/java/it/gov/pagopa/afm/calculator/entity/Bundle.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/TouchpointRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/ValidBundleRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/main/java/it/gov/pagopa/afm/calculator/service/ConfigurationService.java
  src/main/java/it/gov/pagopa/afm/calculator/util/CriteriaBuilder.java
  src/main/resources/application-local.properties
  src/test/java/it/gov/pagopa/afm/calculator/config/MockitoConfig.java
  src/test/resources/responses/getFees.json
  src/test/resources/responses/getFees2.json
  src/test/resources/responses/getFees_noInTransfer.json
Labels: bug
