Repository pagopa/pagopa-afm-calculator, pull requests merged in 2023-09, with the labels that each got.

#105 bug: [PAGOPA-1205] digitalstamp exception
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
Labels: bug, size/small

#106 fix: Upd helm chart
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-node.json
  openapi/openapi.json
  pom.xml
Labels: size/small

#107 feat: [PagoPA-1181]: BIN by range
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  src/main/java/it/gov/pagopa/afm/calculator/entity/IssuerRangeEntity.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/IssuersService.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
Labels: enhancement, size/small, minor
