Repository pagopa/pagopa-afm-calculator, pull requests merged in 2023-05, with the labels that each got.

#77 [PAGOPA-818] kibana integration
  .github/workflows/code_review.yml
  .gitignore
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/resources/application.properties
Labels: ignore-for-release, size/small

#82 Pagopa 918 gestione flag all ccp
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-node.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
  src/main/java/it/gov/pagopa/afm/calculator/controller/ConfigurationController.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/main/java/it/gov/pagopa/afm/calculator/util/CriteriaBuilder.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/afm/calculator/controller/CalculatorControllerTest.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, size/small

#78 Deploy aks
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release_deploy.yml
Labels: size/small

#83 [PagoPA-968] - new onus logic
  .gitignore
  src/main/java/it/gov/pagopa/afm/calculator/model/calculator/Transfer.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/test/java/it/gov/pagopa/afm/calculator/TestUtil.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/responses/getFeesBinNotFound.json
  src/test/resources/responses/getFeesBinNull.json
Labels: bug, enhancement, size/large

#85 [PagoPA-969] new onus logic integration test
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  integration-test/src/step_definitions/support/steps.js
  src/main/java/it/gov/pagopa/afm/calculator/service/ConfigurationService.java
Labels: bug, enhancement, size/large
