Repository pagopa/pagopa-afm-calculator, pull requests merged in 2023-03, with the labels that each got.

#69 fix: [PAGOPA-766] Null pointer exception on payment type
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/main/resources/application-local.properties
  utilities/process_data.py
  utilities/requirements.txt
Labels: bug, size/small

#68 test: Performance test PAGOPA-706
  .devops/performance-test-pipelines.yaml
  .github/workflows/code_review.yml
  helm/values-uat.yaml
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/calculator_getFees.js
  performance-test/src/calculator_getFeesByPsp.js
  performance-test/src/dev.environment.json
  performance-test/src/helpers/calculator_helper.js
  performance-test/src/helpers/cosmosdb_client.js
  performance-test/src/helpers/data.json
  performance-test/src/local.environment.json
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/rampingVU.json
  performance-test/src/test-types/rampingVULessRequests.json
  performance-test/src/test-types/smoke.json
  performance-test/src/test-types/soak.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
Labels: ignore-for-release, size/large

#70 Pagopa 749 psp channel broker
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi-node.json
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOptionByPsp.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PspSearchCriteria.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/util/CriteriaBuilder.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/requests/getFeesPspList.json
Labels: enhancement, size/large
