Repository pagopa/pagopa-afm-calculator, pull requests merged in 2023-02, with the labels that each got.

#54 feat: Storage account and table integration PAGOPA-641
  docker/config/.env
  docker/docker-compose.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-node.json
  openapi/openapi.json
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: enhancement

#56 feat: Add utility script PAGOPA-647
  openapi/openapi-node.json
  openapi/openapi.json
  utilities/process_data.py
Labels: ignore-for-release

#60 Opex dash
  .github/workflows/create_dashboard.yaml
  .identity/.terraform.lock.hcl
  .identity/00_locals.tf
  .identity/00_main.tf
  .identity/00_main.tf.ci
  .identity/00_variables.tf
  .identity/01_data.tf
  .identity/02_application_master.tf
  .identity/02_application_master_auth.tf
  .identity/02_application_pullrequest.tf
  .identity/02_application_pullrequest_auth.tf
  .identity/99_outputs.tf
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/terraform.sh
  .opex/env/dev/backend.ini
  .opex/env/dev/backend.tfvars
  .opex/env/dev/config.yaml
  .opex/env/dev/terraform.tfvars
  .opex/env/prod/backend.ini
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
  .opex/env/uat/backend.ini
  .opex/env/uat/backend.tfvars
  .opex/env/uat/config.yaml
  .opex/env/uat/terraform.tfvars
  openapi/openapi.json
Labels: ignore-for-release

#62 Fix opexd 2
  .github/workflows/create_dashboard.yaml
  .identity/env/prod/backend.tfvars
Labels: ignore-for-release

#65 PAGOPA-711 integration test: modified and added integration tests
  .classpath
  .github/workflows/code_review.yml
  integration-test/src/README.md
  integration-test/src/config/ISSUER_RANGE_for_test.csv
  integration-test/src/config/data.json
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
  src/main/java/it/gov/pagopa/afm/calculator/entity/IssuerRangeEntity.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOptionByPsp.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/main/resources/application-local.properties
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/requests/getFeesDigitalStamp.json
  src/test/resources/requests/getFeesDigitalStamp2.json
  src/test/resources/requests/getFeesNoInTransfer.json
  src/test/resources/responses/getFeesNoInTransfer.json
  src/test/resources/responses/getFeesPaymentTypeNull.json
Labels: enhancement, size/large

#67 [PAGOPA-748] optional bin
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/resources/requests/getFeesBinNull.json
  src/test/resources/requests/getFeesDigitalStamp3.json
  src/test/resources/responses/getFeesBinNull.json
Labels: bug, enhancement, size/small
