Repository pagopa/pagopa-afm-calculator, pull requests merged in 2024-05, with the labels that each got.

#137 Pagopa 1726 afm calculator fix openapi
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOptionMulti.java
Labels: bug, size/small

#139 chore: Fix remove acutor from openapi
  openapi/openapi-v1.json
Labels: size/small

#142 PAGOPA-1733-config-afm-calculator-aggiunta-mooney-in-whitelist
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  src/test/resources/application.properties
Labels: enhancement, ignore-for-release, size/small

#144 grouping dataCart into data
  integration-test/src/config/data.json
  integration-test/src/config/dataCart.json
  integration-test/src/features/getFeesByPspMulti.feature
  integration-test/src/features/getFeesMulti.feature
Labels: bug, ignore-for-release, size/large

#145 PAGOPA-1761 changing pointers from app-gw to apim
  .opex/internal/v1/env/prod/config.yaml
  .opex/internal/v2/env/prod/config.yaml
  .opex/node/v1/env/prod/config.yaml
  .opex/node/v2/env/prod/config.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
  src/main/java/it/gov/pagopa/afm/calculator/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/afm/calculator/exception/AppError.java
Labels: size/small, patch

#147 PAGOPA-1778 change whitelist to blacklist for psp
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/util/CriteriaBuilder.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: enhancement, size/large, minor
