Repository pagopa/pagopa-afm-calculator, pull requests merged in 2024-03, with the labels that each got.

#130 PAGOPA-1495 modifying doc and openapi
  .github/workflows/check_pr.yml
  .github/workflows/update_infra.yml
  .opex/internal/env/prod/config.yaml
  .opex/node/env/prod/config.yaml
  README.md
  openapi/generate_openapi.sh
  openapi/generate_openapi_node.py
  openapi/generate_openapi_v1_v2.sh
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-node.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  openapi/openapi.json
  openapi/openapi_v1.json
  openapi/openapi_v2.json
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/afm/calculator/OpenApiGenerationTest.java
  src/test/resources/application.properties
Labels: size/large

#131 chore: Upd prod helm
  helm/values-prod.yaml
Labels: size/small

#134 Pagopa 1594 opex gec carrello
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  openapi/openapi-v1.json
Labels: bug, enhancement, size/small

#135 adding v2 opex
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/integration_test.yml
  .opex/internal/v1/env/prod/backend.ini
  .opex/internal/v1/env/prod/backend.tfvars
  .opex/internal/v1/env/prod/config.yaml
  .opex/internal/v1/env/prod/terraform.tfvars
  .opex/internal/v2/env/prod/backend.ini
  .opex/internal/v2/env/prod/backend.tfvars
  .opex/internal/v2/env/prod/config.yaml
  .opex/internal/v2/env/prod/terraform.tfvars
  .opex/node/v1/env/prod/backend.ini
  .opex/node/v1/env/prod/backend.tfvars
  .opex/node/v1/env/prod/config.yaml
  .opex/node/v1/env/prod/terraform.tfvars
  .opex/node/v2/env/prod/backend.ini
  .opex/node/v2/env/prod/backend.tfvars
  .opex/node/v2/env/prod/config.yaml
  .opex/node/v2/env/prod/terraform.tfvars
Labels: enhancement, size/small

#136 chore: Upd opex
  .opex/internal/v1/env/prod/config.yaml
  .opex/internal/v2/env/prod/backend.tfvars
  .opex/internal/v2/env/prod/config.yaml
  .opex/node/v1/env/prod/config.yaml
  .opex/node/v2/env/prod/backend.tfvars
  .opex/node/v2/env/prod/config.yaml
Labels: size/small
