Repository pagopa/pagopa-afm-calculator, pull requests merged in 2025-06, with the labels that each got.

#172 [PAGOPA-3071] feat: implemented bundle sorting logic
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
  src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
  src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
  src/main/java/it/gov/pagopa/afm/calculator/util/CalculatorUtil.java
  src/test/java/it/gov/pagopa/afm/calculator/TestUtil.java
  src/test/java/it/gov/pagopa/afm/calculator/controller/CalculatorControllerTest.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/java/it/gov/pagopa/afm/calculator/util/CalculatorUtilTest.java
Labels: size/large, patch

#174 [PAGOPA-3104] fix: update openapi queryparams
  openapi/openapi-node-v2.json
  openapi/openapi-v2.json
Labels: size/small, patch

#176 chore: adding new integration tests for the new ordering methods Pagopa-3072
  .github/workflows/integration_test.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .terraform-version
  integration-test/src/config/.env.uat
  integration-test/src/config/data.json
  integration-test/src/features/getFeeByPsp.feature
  integration-test/src/features/getFees.feature
  integration-test/src/features/getFeesByPspMulti.feature
  integration-test/src/features/getFeesMulti.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/steps.js
Labels: enhancement, ignore-for-release, size/large, skip
