Repository pagopa/pagopa-afm-calculator, pull requests merged in 2025-09, with the labels that each got.

#193 feat: [PAGOPA-3272] Remove bin field from searchPaymentMethods
  integration-test/src/features/getPaymentMethodsRangeAmount.feature
  integration-test/src/features/getPaymentMethodsTotalAmount.feature
  integration-test/src/features/getPaymentMethodsUserDeviceKo.feature
  integration-test/src/features/getPaymentMethodsUserDeviceOk.feature
  integration-test/src/features/getPaymentMethodsUserTouchpointKo.feature
  integration-test/src/features/getPaymentMethodsUserTouchpointOk.feature
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/PaymentMethodRequest.java
  src/main/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsService.java
  src/test/resources/requests/paymentOptionsSearch.json
Labels: size/large, minor

#195 [PagoPA-3275] - new getpaymentmethodbyid api
  performance-test/src/calculator_getPaymentMethodById.js
  performance-test/src/helpers/calculator_helper.js
  src/main/java/it/gov/pagopa/afm/calculator/controller/PaymentMethodsController.java
  src/main/java/it/gov/pagopa/afm/calculator/exception/AppError.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/PaymentMethodRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsService.java
  src/test/java/it/gov/pagopa/afm/calculator/controller/PaymentMethodsControllerTest.java
  src/test/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsServiceTest.java
Labels: enhancement, size/large, minor

#200 hotfix filter pm
  src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
  src/test/java/it/gov/pagopa/afm/calculator/repository/CosmosRepositoryTest.java
Labels: bug, size/small, patch

#199 fix: snakeCase to camelCase
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/afm/calculator/controller/PaymentMethodsController.java
  src/main/java/it/gov/pagopa/afm/calculator/model/PaymentMethodResponse.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/Metadata.java
  src/main/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsService.java
  src/test/java/it/gov/pagopa/afm/calculator/controller/PaymentMethodsControllerTest.java
  src/test/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsServiceTest.java
Labels: size/large, patch
