Repository pagopa/pagopa-afm-calculator, pull requests merged in 2025-07, with the labels that each got.

#178 Dashboard
  .github/workflows/create_dashboard.yaml
  .opex/v1/env/prod/backend.ini
  .opex/v1/env/prod/backend.tfvars
  .opex/v1/env/prod/config.yaml
  .opex/v1/env/prod/terraform.tfvars
  .opex/v2/env/prod/backend.ini
  .opex/v2/env/prod/backend.tfvars
  .opex/v2/env/prod/config.yaml
  .opex/v2/env/prod/terraform.tfvars
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
Labels: size/large

#179 feat: payment methods search
  docker/run_docker.sh
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/java/it/gov/pagopa/afm/calculator/controller/PaymentMethodsController.java
  src/main/java/it/gov/pagopa/afm/calculator/entity/PaymentMethod.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/FeeRange.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/PaymentMethodRequest.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/PaymentMethodsResponse.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/Language.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/MethodManagement.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/PaymentMethodDisabledReason.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/PaymentMethodGroup.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/PaymentMethodStatus.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/UserDevice.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/UserTouchpoint.java
  src/main/java/it/gov/pagopa/afm/calculator/repository/PaymentMethodRepository.java
  src/main/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsService.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/afm/calculator/config/MockitoConfig.java
  src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
  src/test/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsServiceTest.java
  src/test/resources/requests/paymentOptionsSearch.json
Labels: size/large, minor

#181 fix: rollback transferCategory notNull
  src/main/java/it/gov/pagopa/afm/calculator/model/TransferListItem.java
Labels: size/small, patch

#183 fix: switch payment method openapi to v1
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: size/large

#182 [PAGOPA-3134] feat: Add integration test for GMP API
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/config/payment-methods-range-amount.json
  integration-test/src/config/payment-methods-total-amount.json
  integration-test/src/config/payment-methods-user-device-ko.json
  integration-test/src/config/payment-methods-user-device-ok.json
  integration-test/src/config/payment-methods-user-touchpoint-ko.json
  integration-test/src/config/payment-methods-user-touchpoint-ok.json
  integration-test/src/features/getPaymentMethodsRangeAmount.feature
  integration-test/src/features/getPaymentMethodsTotalAmount.feature
  integration-test/src/features/getPaymentMethodsUserDeviceKo.feature
  integration-test/src/features/getPaymentMethodsUserDeviceOk.feature
  integration-test/src/features/getPaymentMethodsUserTouchpointKo.feature
  integration-test/src/features/getPaymentMethodsUserTouchpointOk.feature
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi-internal.json
  openapi/openapi-node-v1.json
  openapi/openapi-node-v2.json
  openapi/openapi-v1-dev-uat.json
  openapi/openapi-v1.json
  openapi/openapi-v2.json
  pom.xml
Labels: ignore-for-release, size/large, skip

#185 chore: perf test GMP Pagopa-3200
  .devops/performance-test-pipelines.yaml
  performance-test/docker-compose.yaml
  performance-test/src/calculator_getFeesMulti.js
  performance-test/src/calculator_searchPaymentMethods.js
  performance-test/src/env/dev.environment.json
  performance-test/src/env/local.environment.json
  performance-test/src/env/uat.environment.json
  performance-test/src/helpers/calculator_helper.js
  performance-test/src/test-types/constant.json
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/PaymentMethodRequest.java
  src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/enums/PaymentMethodGroup.java
Labels: enhancement, size/small, patch
